export const INIT          = 'INIT'
export const LOAD          = 'LOAD'
export const UNSELECT      = 'UNSELECT'
export const SELECT        = 'SELECT'
export const ADD_REGION    = 'ADD_REGION'
export const CLEAR_REGIONS = 'CLEAR_REGIONS'
